version: '3.1'
services:
  poracle:
    image: kartuludus/poracle:develop
    container_name: poracle
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      DB_HOST: poracle-db
      DB_USER: poracleuser
      DB_PASSWORD: YourStrongPassw0rd!
      DB_DATABASE: poracledb
      HOST: 0.0.0.0
    ports:
      - 3030:3030
    volumes:
      - ./config/:/PoracleJS/config/
    depends_on:
      - poracle-db

  poracle-db:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: poracle-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongRootPassw0rd!
      MYSQL_DATABASE: poracledb
      MYSQL_USER: poracleuser
      MYSQL_PASSWORD: YourStrongPassw0rd!
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
    driver: local
